import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { StoreStateContextProvider } from './utils/context/page'
import { Provider } from "./provider";
const inter = Inter({ subsets: ["latin"] });
import { useQuery } from "@tanstack/react-query";
export const metadata: Metadata = {
  title: "Finazon Financial Market Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <StoreStateContextProvider>
      <body className={inter.className}><Provider>{children}</Provider></body>
      </StoreStateContextProvider>
    </html>
  );
}
